name = "-iqherb"
compatibility_date = "2024-12-04"

[build]
command = ""
cwd = ""
watch_dir = ""

[build.upload]
format = "service-worker"
dir = "build/web"
main = "./build/web/index.html"

[[pages_build_output_dir]]
directory = "build/web"
